# Appveyor configuration template for Rust using rustup for Rust installation
# https://github.com/starkat99/appveyor-rust

os: Visual Studio 2015

environment:
  channel: stable
  target: i686-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build_script:
  - cargo-build --release --verbose %cargoflags%

after_build:
  - 7z a inno_updater.zip %APPVEYOR_BUILD_FOLDER%\target\i686-pc-windows-msvc\release\inno_updater.exe
  
test: off

artifacts:
  - path: inno_updater.zip
    name: Inno Updater