[package]
name = "inno_updater"
version = "0.1.0"
authors = ["Joao Moreno <mail@joaomoreno.com>"]

[dependencies]
byteorder = "1"
crc = "^1.0.0"
native-windows-gui = "0.2.0"
user32-sys = "0.1.2"

[profile.release]
lto = true
panic = 'abort'