[package]
name = "inno_updater"
version = "0.1.0"
authors = ["Joao Moreno <mail@joaomoreno.com>"]

[dependencies]
byteorder = "1"
crc = "^1.0.0"

[dependencies.clap]
version = "^2.29.1"
default-features = false

[profile.release]
lto = true
panic = 'abort'